### PR TITLE
#162569680 A user can create an account

### PR DESCRIPTION
**Pull request by kathy254**
**What does this PR do?**
--------------------------------
This pull request creates a signup page where a user can create an account

**Description of tasks to be completed**
------------------------------------------
_The following are the tasks to be completed_
-  Create html for the signup page
- Create css for the signup page

**How should you manually test this?**
---------------------------------------------------
1. Clone this repository
    `$ git clone https://github.com/kathy254/StackOverflow-Lite-UI.git`

5. cd into folder
    `$ cd StackOverflow-Lite-UI`

6. Switch to the current branch
    `$ ft-signup-account-162569680`

7. Open `signup.html` on your browser

Pivotal tracker story associated with this PR
---------------------------------------------
#162569680

**Screenshot**
---------------------

screenshot from 2018-12-12 14-20-41

### CODE REVIEW

**Comment by jmusila** [comment]
Nice work

**Comment by wachiranduati** [comment]
Looks amazing.

**Comment by cod3smith** [comment]
Looks great. Good work.

**Comment by emdeechege** [comment]
Nice look..

**Comment by georgekkk** [comment]
looks good

**Comment by Thabuks** [comment]
Awesome.

**Comment by Ogutu-Brian** [comment]
Wow! This is amazing, @kathy254

**Comment by NgachaIan** [comment]
great work!

**Comment by munniomer** [comment]
Nice work

**Comment by mdn-network** [comment]
A good one here

**Comment by tirgei** [comment]
Nice

**Comment by Siffersari** [comment]
Wow, you really described that PR. Great job on that and the website design.

**Comment by Ogutu-Brian** [comment]
> A good one here

Thanks @Philipotieno

**Comment by Ogutu-Brian** [comment]
> Nice

Thanks @tirgei

**Comment by Ogutu-Brian** [comment]
> Wow, you really described that PR. Great job on that and the website design.

Thanks @Siffersari

**Comment by kathy254** [comment]
screenshot from 2018-12-12 16-02-30

**Comment by SolomonMacharia** [comment]
Nice work.

**Pull request merged**
